[package]
name = "proto-build"
version = "0.1.0"
authors = ["Stephen Cirner <scirner@figure.com>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.13"
prost-build = "0.13"
tonic = "0.13"
tonic-build = "0.14"
regex = "1"
walkdir = "2.5"
