[package]
name = "proto-build"
version = "0.1.0"
authors = ["Stephen Cirner <scirner@figure.com>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.11"
prost-build = "0.11"
tonic = "0.9"
tonic-build = "0.8"
regex = "1"
walkdir = "2.3"
