// This file is @generated by prost-build.
/// MsgAssessCustomMsgFeeRequest defines an sdk.Msg type
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgAssessCustomMsgFeeRequest {
    /// optional short name for custom msg fee, this will be emitted as a property of the event
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// amount of additional fee that must be paid
    #[prost(message, optional, tag = "2")]
    pub amount: ::core::option::Option<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// optional recipient address, the basis points amount is sent to the recipient
    #[prost(string, tag = "3")]
    pub recipient: ::prost::alloc::string::String,
    /// the signer of the msg
    #[prost(string, tag = "4")]
    pub from: ::prost::alloc::string::String,
    /// optional basis points 0 - 10,000 for recipient defaults to 10,000
    #[prost(string, tag = "5")]
    pub recipient_basis_points: ::prost::alloc::string::String,
}
/// MsgAssessCustomMsgFeeResponse defines the Msg/AssessCustomMsgFeee response type.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgAssessCustomMsgFeeResponse {}
/// AddMsgFeeProposal defines a governance proposal to add additional msg based fee
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgAddMsgFeeProposalRequest {
    /// type url of msg to add fee
    #[prost(string, tag = "1")]
    pub msg_type_url: ::prost::alloc::string::String,
    /// additional fee for msg type
    #[prost(message, optional, tag = "2")]
    pub additional_fee: ::core::option::Option<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// optional recipient to receive basis points
    #[prost(string, tag = "3")]
    pub recipient: ::prost::alloc::string::String,
    /// basis points to use when recipient is present (1 - 10,000)
    #[prost(string, tag = "4")]
    pub recipient_basis_points: ::prost::alloc::string::String,
    /// the signing authority for the proposal
    #[prost(string, tag = "5")]
    pub authority: ::prost::alloc::string::String,
}
/// MsgAddMsgFeeProposalResponse defines the Msg/AddMsgFeeProposal response type
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgAddMsgFeeProposalResponse {}
/// UpdateMsgFeeProposal defines a governance proposal to update a current msg based fee
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateMsgFeeProposalRequest {
    /// type url of msg to update fee
    #[prost(string, tag = "1")]
    pub msg_type_url: ::prost::alloc::string::String,
    /// additional fee for msg type
    #[prost(message, optional, tag = "2")]
    pub additional_fee: ::core::option::Option<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// optional recipient to receive basis points
    #[prost(string, tag = "3")]
    pub recipient: ::prost::alloc::string::String,
    /// basis points to use when recipient is present (1 - 10,000)
    #[prost(string, tag = "4")]
    pub recipient_basis_points: ::prost::alloc::string::String,
    /// the signing authority for the proposal
    #[prost(string, tag = "5")]
    pub authority: ::prost::alloc::string::String,
}
/// MsgUpdateMsgFeeProposalResponse defines the Msg/RemoveMsgFeeProposal response type
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateMsgFeeProposalResponse {}
/// RemoveMsgFeeProposal defines a governance proposal to delete a current msg based fee
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgRemoveMsgFeeProposalRequest {
    /// type url of msg fee to remove
    #[prost(string, tag = "1")]
    pub msg_type_url: ::prost::alloc::string::String,
    /// the signing authority for the proposal
    ///
    ///
    #[prost(string, tag = "2")]
    pub authority: ::prost::alloc::string::String,
}
/// MsgRemoveMsgFeeProposalResponse defines the Msg/RemoveMsgFeeProposal response type
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgRemoveMsgFeeProposalResponse {}
/// UpdateNhashPerUsdMilProposal defines a governance proposal to update the nhash per usd mil param
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateNhashPerUsdMilProposalRequest {
    /// nhash_per_usd_mil is number of nhash per usd mil
    #[prost(uint64, tag = "1")]
    pub nhash_per_usd_mil: u64,
    /// the signing authority for the proposal
    ///
    ///
    #[prost(string, tag = "2")]
    pub authority: ::prost::alloc::string::String,
}
/// MsgUpdateNhashPerUsdMilProposalResponse defines the Msg/UpdateNhashPerUsdMilProposal response type
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateNhashPerUsdMilProposalResponse {}
/// UpdateConversionFeeDenomProposal defines a governance proposal to update the msg fee conversion denom
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateConversionFeeDenomProposalRequest {
    /// conversion_fee_denom is the denom that usd will be converted to
    #[prost(string, tag = "1")]
    pub conversion_fee_denom: ::prost::alloc::string::String,
    /// the signing authority for the proposal
    ///
    ///
    #[prost(string, tag = "2")]
    pub authority: ::prost::alloc::string::String,
}
/// MsgUpdateConversionFeeDenomProposalResponse defines the Msg/UpdateConversionFeeDenomProposal response type
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateConversionFeeDenomProposalResponse {}
/// Generated client implementations.
#[cfg(feature = "grpc")]
#[cfg_attr(docsrs, doc(cfg(feature = "grpc")))]
pub mod msg_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// Msg defines the msgfees Msg service.
    #[derive(Debug, Clone)]
    pub struct MsgClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "grpc-transport")]
    #[cfg_attr(docsrs, doc(cfg(feature = "grpc-transport")))]
    impl MsgClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MsgClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> MsgClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + Send + Sync,
        {
            MsgClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// AssessCustomMsgFee endpoint executes the additional fee charges.
        /// This will only emit the event and not persist it to the keeper.  Fees are handled with the custom msg fee handlers
        /// Use Case: smart contracts will be able to charge additional fees and direct partial funds to specified recipient
        /// for executing contracts
        pub async fn assess_custom_msg_fee(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgAssessCustomMsgFeeRequest>,
        ) -> std::result::Result<tonic::Response<super::MsgAssessCustomMsgFeeResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/provenance.msgfees.v1.Msg/AssessCustomMsgFee",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "provenance.msgfees.v1.Msg",
                "AssessCustomMsgFee",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// AddMsgFeeProposal defines a governance proposal to add additional msg based fee
        pub async fn add_msg_fee_proposal(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgAddMsgFeeProposalRequest>,
        ) -> std::result::Result<tonic::Response<super::MsgAddMsgFeeProposalResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/provenance.msgfees.v1.Msg/AddMsgFeeProposal",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "provenance.msgfees.v1.Msg",
                "AddMsgFeeProposal",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// UpdateMsgFeeProposal defines a governance proposal to update a current msg based fee
        pub async fn update_msg_fee_proposal(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUpdateMsgFeeProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateMsgFeeProposalResponse>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/provenance.msgfees.v1.Msg/UpdateMsgFeeProposal",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "provenance.msgfees.v1.Msg",
                "UpdateMsgFeeProposal",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// RemoveMsgFeeProposal defines a governance proposal to delete a current msg based fee
        pub async fn remove_msg_fee_proposal(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgRemoveMsgFeeProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MsgRemoveMsgFeeProposalResponse>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/provenance.msgfees.v1.Msg/RemoveMsgFeeProposal",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "provenance.msgfees.v1.Msg",
                "RemoveMsgFeeProposal",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// UpdateNhashPerUsdMilProposal defines a governance proposal to update the nhash per usd mil param
        pub async fn update_nhash_per_usd_mil_proposal(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUpdateNhashPerUsdMilProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateNhashPerUsdMilProposalResponse>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/provenance.msgfees.v1.Msg/UpdateNhashPerUsdMilProposal",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "provenance.msgfees.v1.Msg",
                "UpdateNhashPerUsdMilProposal",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// UpdateConversionFeeDenomProposal defines a governance proposal to update the msg fee conversion denom
        pub async fn update_conversion_fee_denom_proposal(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUpdateConversionFeeDenomProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateConversionFeeDenomProposalResponse>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/provenance.msgfees.v1.Msg/UpdateConversionFeeDenomProposal",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "provenance.msgfees.v1.Msg",
                "UpdateConversionFeeDenomProposal",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "grpc")]
#[cfg_attr(docsrs, doc(cfg(feature = "grpc")))]
pub mod msg_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MsgServer.
    #[async_trait]
    pub trait Msg: Send + Sync + 'static {
        /// AssessCustomMsgFee endpoint executes the additional fee charges.
        /// This will only emit the event and not persist it to the keeper.  Fees are handled with the custom msg fee handlers
        /// Use Case: smart contracts will be able to charge additional fees and direct partial funds to specified recipient
        /// for executing contracts
        async fn assess_custom_msg_fee(
            &self,
            request: tonic::Request<super::MsgAssessCustomMsgFeeRequest>,
        ) -> std::result::Result<tonic::Response<super::MsgAssessCustomMsgFeeResponse>, tonic::Status>;
        /// AddMsgFeeProposal defines a governance proposal to add additional msg based fee
        async fn add_msg_fee_proposal(
            &self,
            request: tonic::Request<super::MsgAddMsgFeeProposalRequest>,
        ) -> std::result::Result<tonic::Response<super::MsgAddMsgFeeProposalResponse>, tonic::Status>;
        /// UpdateMsgFeeProposal defines a governance proposal to update a current msg based fee
        async fn update_msg_fee_proposal(
            &self,
            request: tonic::Request<super::MsgUpdateMsgFeeProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateMsgFeeProposalResponse>,
            tonic::Status,
        >;
        /// RemoveMsgFeeProposal defines a governance proposal to delete a current msg based fee
        async fn remove_msg_fee_proposal(
            &self,
            request: tonic::Request<super::MsgRemoveMsgFeeProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MsgRemoveMsgFeeProposalResponse>,
            tonic::Status,
        >;
        /// UpdateNhashPerUsdMilProposal defines a governance proposal to update the nhash per usd mil param
        async fn update_nhash_per_usd_mil_proposal(
            &self,
            request: tonic::Request<super::MsgUpdateNhashPerUsdMilProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateNhashPerUsdMilProposalResponse>,
            tonic::Status,
        >;
        /// UpdateConversionFeeDenomProposal defines a governance proposal to update the msg fee conversion denom
        async fn update_conversion_fee_denom_proposal(
            &self,
            request: tonic::Request<super::MsgUpdateConversionFeeDenomProposalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateConversionFeeDenomProposalResponse>,
            tonic::Status,
        >;
    }
    /// Msg defines the msgfees Msg service.
    #[derive(Debug)]
    pub struct MsgServer<T: Msg> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T: Msg> MsgServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MsgServer<T>
    where
        T: Msg,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/provenance.msgfees.v1.Msg/AssessCustomMsgFee" => {
                    #[allow(non_camel_case_types)]
                    struct AssessCustomMsgFeeSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg> tonic::server::UnaryService<super::MsgAssessCustomMsgFeeRequest>
                        for AssessCustomMsgFeeSvc<T>
                    {
                        type Response = super::MsgAssessCustomMsgFeeResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgAssessCustomMsgFeeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::assess_custom_msg_fee(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AssessCustomMsgFeeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/provenance.msgfees.v1.Msg/AddMsgFeeProposal" => {
                    #[allow(non_camel_case_types)]
                    struct AddMsgFeeProposalSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg> tonic::server::UnaryService<super::MsgAddMsgFeeProposalRequest>
                        for AddMsgFeeProposalSvc<T>
                    {
                        type Response = super::MsgAddMsgFeeProposalResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgAddMsgFeeProposalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::add_msg_fee_proposal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddMsgFeeProposalSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/provenance.msgfees.v1.Msg/UpdateMsgFeeProposal" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateMsgFeeProposalSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg> tonic::server::UnaryService<super::MsgUpdateMsgFeeProposalRequest>
                        for UpdateMsgFeeProposalSvc<T>
                    {
                        type Response = super::MsgUpdateMsgFeeProposalResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgUpdateMsgFeeProposalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::update_msg_fee_proposal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateMsgFeeProposalSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/provenance.msgfees.v1.Msg/RemoveMsgFeeProposal" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveMsgFeeProposalSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg> tonic::server::UnaryService<super::MsgRemoveMsgFeeProposalRequest>
                        for RemoveMsgFeeProposalSvc<T>
                    {
                        type Response = super::MsgRemoveMsgFeeProposalResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgRemoveMsgFeeProposalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::remove_msg_fee_proposal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveMsgFeeProposalSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/provenance.msgfees.v1.Msg/UpdateNhashPerUsdMilProposal" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateNhashPerUsdMilProposalSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg>
                        tonic::server::UnaryService<super::MsgUpdateNhashPerUsdMilProposalRequest>
                        for UpdateNhashPerUsdMilProposalSvc<T>
                    {
                        type Response = super::MsgUpdateNhashPerUsdMilProposalResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgUpdateNhashPerUsdMilProposalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::update_nhash_per_usd_mil_proposal(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateNhashPerUsdMilProposalSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/provenance.msgfees.v1.Msg/UpdateConversionFeeDenomProposal" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateConversionFeeDenomProposalSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg>
                        tonic::server::UnaryService<
                            super::MsgUpdateConversionFeeDenomProposalRequest,
                        > for UpdateConversionFeeDenomProposalSvc<T>
                    {
                        type Response = super::MsgUpdateConversionFeeDenomProposalResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::MsgUpdateConversionFeeDenomProposalRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::update_conversion_fee_denom_proposal(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateConversionFeeDenomProposalSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    Ok(http::Response::builder()
                        .status(200)
                        .header("grpc-status", tonic::Code::Unimplemented as i32)
                        .header(
                            http::header::CONTENT_TYPE,
                            tonic::metadata::GRPC_CONTENT_TYPE,
                        )
                        .body(empty_body())
                        .unwrap())
                }),
            }
        }
    }
    impl<T: Msg> Clone for MsgServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: Msg> tonic::server::NamedService for MsgServer<T> {
        const NAME: &'static str = "provenance.msgfees.v1.Msg";
    }
}
/// Params defines the set of params for the msgfees module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Params {
    /// floor_gas_price is the constant used to calculate fees when gas fees shares denom with msg fee.
    ///
    /// Conversions:
    ///    - x nhash/usd-mil = 1,000,000/x usd/hash
    ///    - y usd/hash = 1,000,000/y nhash/usd-mil
    ///
    /// Examples:
    ///    - 40,000,000 nhash/usd-mil = 1,000,000/40,000,000 usd/hash = $0.025/hash,
    ///    - $0.040/hash = 1,000,000/0.040 nhash/usd-mil = 25,000,000 nhash/usd-mil
    #[prost(message, optional, tag = "2")]
    pub floor_gas_price: ::core::option::Option<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// nhash_per_usd_mil is the total nhash per usd mil for converting usd to nhash.
    #[prost(uint64, tag = "3")]
    pub nhash_per_usd_mil: u64,
    /// conversion_fee_denom is the denom usd is converted to.
    #[prost(string, tag = "4")]
    pub conversion_fee_denom: ::prost::alloc::string::String,
}
/// MsgFee is the core of what gets stored on the blockchain to define a msg-based fee.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgFee {
    /// msg_type_url is the type-url of the message with the added fee, e.g. "/cosmos.bank.v1beta1.MsgSend".
    #[prost(string, tag = "1")]
    pub msg_type_url: ::prost::alloc::string::String,
    /// additional_fee is the extra fee that is required for the given message type (can be in any denom).
    #[prost(message, optional, tag = "2")]
    pub additional_fee: ::core::option::Option<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// recipient is an option address that will receive a portion of the additional fee.
    /// There can only be a recipient if the recipient_basis_points is not zero.
    #[prost(string, tag = "3")]
    pub recipient: ::prost::alloc::string::String,
    /// recipient_basis_points is an optional portion of the additional fee to be sent to the recipient.
    /// Must be between 0 and 10,000 (inclusive).
    ///
    /// If there is a recipient, this must not be zero. If there is not a recipient, this must be zero.
    ///
    /// The recipient will receive additional_fee * recipient_basis_points / 10,000.
    /// The fee collector will receive the rest, i.e. additional_fee * (10,000 - recipient_basis_points) / 10,000.
    #[prost(uint32, tag = "4")]
    pub recipient_basis_points: u32,
}
/// EventMsgFee final event property for msg fee on type
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventMsgFee {
    #[prost(string, tag = "1")]
    pub msg_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub count: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub total: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub recipient: ::prost::alloc::string::String,
}
/// EventMsgFees event emitted with summary of msg fees
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventMsgFees {
    #[prost(message, repeated, tag = "1")]
    pub msg_fees: ::prost::alloc::vec::Vec<EventMsgFee>,
}
/// QueryParamsRequest is the request type for the Query/Params RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {}
/// QueryParamsResponse is the response type for the Query/Params RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    /// params defines the parameters of the module.
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
}
/// QueryAllMsgFeesRequest queries all Msg which have fees associated with them.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryAllMsgFeesRequest {
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "2")]
    pub pagination:
        ::core::option::Option<cosmos_sdk_proto::cosmos::base::query::v1beta1::PageRequest>,
}
/// response for querying all msg's with fees associated with them
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryAllMsgFeesResponse {
    #[prost(message, repeated, tag = "1")]
    pub msg_fees: ::prost::alloc::vec::Vec<MsgFee>,
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "2")]
    pub pagination:
        ::core::option::Option<cosmos_sdk_proto::cosmos::base::query::v1beta1::PageResponse>,
}
/// CalculateTxFeesRequest is the request type for the Query RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CalculateTxFeesRequest {
    /// tx_bytes is the transaction to simulate.
    #[prost(bytes = "vec", tag = "1")]
    pub tx_bytes: ::prost::alloc::vec::Vec<u8>,
    /// default_base_denom is used to set the denom used for gas fees
    /// if not set it will default to nhash.
    #[prost(string, tag = "2")]
    pub default_base_denom: ::prost::alloc::string::String,
    /// gas_adjustment is the adjustment factor to be multiplied against the estimate returned by the tx simulation
    #[prost(float, tag = "3")]
    pub gas_adjustment: f32,
}
/// CalculateTxFeesResponse is the response type for the Query RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CalculateTxFeesResponse {
    /// additional_fees are the amount of coins to be for addition msg fees
    #[prost(message, repeated, tag = "1")]
    pub additional_fees: ::prost::alloc::vec::Vec<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// total_fees are the total amount of fees needed for the transactions (msg fees + gas fee)
    /// note: the gas fee is calculated with the floor gas price module param.
    #[prost(message, repeated, tag = "2")]
    pub total_fees: ::prost::alloc::vec::Vec<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// estimated_gas is the amount of gas needed for the transaction
    #[prost(uint64, tag = "3")]
    pub estimated_gas: u64,
}
/// Generated client implementations.
#[cfg(feature = "grpc")]
#[cfg_attr(docsrs, doc(cfg(feature = "grpc")))]
pub mod query_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// Query defines the gRPC querier service for marker module.
    #[derive(Debug, Clone)]
    pub struct QueryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "grpc-transport")]
    #[cfg_attr(docsrs, doc(cfg(feature = "grpc-transport")))]
    impl QueryClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QueryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + Send + Sync,
        {
            QueryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Params queries the parameters for x/msgfees
        pub async fn params(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryParamsRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryParamsResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/provenance.msgfees.v1.Query/Params");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("provenance.msgfees.v1.Query", "Params"));
            self.inner.unary(req, path, codec).await
        }
        /// Query all Msgs which have fees associated with them.
        pub async fn query_all_msg_fees(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryAllMsgFeesRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryAllMsgFeesResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/provenance.msgfees.v1.Query/QueryAllMsgFees",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "provenance.msgfees.v1.Query",
                "QueryAllMsgFees",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// CalculateTxFees simulates executing a transaction for estimating gas usage and additional fees.
        pub async fn calculate_tx_fees(
            &mut self,
            request: impl tonic::IntoRequest<super::CalculateTxFeesRequest>,
        ) -> std::result::Result<tonic::Response<super::CalculateTxFeesResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/provenance.msgfees.v1.Query/CalculateTxFees",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "provenance.msgfees.v1.Query",
                "CalculateTxFees",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "grpc")]
#[cfg_attr(docsrs, doc(cfg(feature = "grpc")))]
pub mod query_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with QueryServer.
    #[async_trait]
    pub trait Query: Send + Sync + 'static {
        /// Params queries the parameters for x/msgfees
        async fn params(
            &self,
            request: tonic::Request<super::QueryParamsRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryParamsResponse>, tonic::Status>;
        /// Query all Msgs which have fees associated with them.
        async fn query_all_msg_fees(
            &self,
            request: tonic::Request<super::QueryAllMsgFeesRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryAllMsgFeesResponse>, tonic::Status>;
        /// CalculateTxFees simulates executing a transaction for estimating gas usage and additional fees.
        async fn calculate_tx_fees(
            &self,
            request: tonic::Request<super::CalculateTxFeesRequest>,
        ) -> std::result::Result<tonic::Response<super::CalculateTxFeesResponse>, tonic::Status>;
    }
    /// Query defines the gRPC querier service for marker module.
    #[derive(Debug)]
    pub struct QueryServer<T: Query> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T: Query> QueryServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for QueryServer<T>
    where
        T: Query,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/provenance.msgfees.v1.Query/Params" => {
                    #[allow(non_camel_case_types)]
                    struct ParamsSvc<T: Query>(pub Arc<T>);
                    impl<T: Query> tonic::server::UnaryService<super::QueryParamsRequest> for ParamsSvc<T> {
                        type Response = super::QueryParamsResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryParamsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move { <T as Query>::params(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ParamsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/provenance.msgfees.v1.Query/QueryAllMsgFees" => {
                    #[allow(non_camel_case_types)]
                    struct QueryAllMsgFeesSvc<T: Query>(pub Arc<T>);
                    impl<T: Query> tonic::server::UnaryService<super::QueryAllMsgFeesRequest>
                        for QueryAllMsgFeesSvc<T>
                    {
                        type Response = super::QueryAllMsgFeesResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryAllMsgFeesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::query_all_msg_fees(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = QueryAllMsgFeesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/provenance.msgfees.v1.Query/CalculateTxFees" => {
                    #[allow(non_camel_case_types)]
                    struct CalculateTxFeesSvc<T: Query>(pub Arc<T>);
                    impl<T: Query> tonic::server::UnaryService<super::CalculateTxFeesRequest>
                        for CalculateTxFeesSvc<T>
                    {
                        type Response = super::CalculateTxFeesResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CalculateTxFeesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::calculate_tx_fees(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CalculateTxFeesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    Ok(http::Response::builder()
                        .status(200)
                        .header("grpc-status", tonic::Code::Unimplemented as i32)
                        .header(
                            http::header::CONTENT_TYPE,
                            tonic::metadata::GRPC_CONTENT_TYPE,
                        )
                        .body(empty_body())
                        .unwrap())
                }),
            }
        }
    }
    impl<T: Query> Clone for QueryServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: Query> tonic::server::NamedService for QueryServer<T> {
        const NAME: &'static str = "provenance.msgfees.v1.Query";
    }
}
/// GenesisState contains a set of msg fees, persisted from the store
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    /// params defines all the parameters of the module.
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
    /// msg_based_fees are the additional fees on specific tx msgs
    #[prost(message, repeated, tag = "2")]
    pub msg_fees: ::prost::alloc::vec::Vec<MsgFee>,
}
/// AddMsgFeeProposal defines a governance proposal to add additional msg based fee
/// Deprecated: This message is no longer usable. It is only still included for
/// backwards compatibility (e.g. looking up old governance proposals).
/// It is replaced by providing a MsgAddMsgFeeProposalRequest in a governance proposal.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddMsgFeeProposal {
    /// propsal title
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    /// propsal description
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// type url of msg to add fee
    #[prost(string, tag = "3")]
    pub msg_type_url: ::prost::alloc::string::String,
    /// additional fee for msg type
    #[prost(message, optional, tag = "4")]
    pub additional_fee: ::core::option::Option<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// optional recipient to recieve basis points
    #[prost(string, tag = "5")]
    pub recipient: ::prost::alloc::string::String,
    /// basis points to use when recipient is present (1 - 10,000)
    #[prost(string, tag = "6")]
    pub recipient_basis_points: ::prost::alloc::string::String,
}
/// UpdateMsgFeeProposal defines a governance proposal to update a current msg based fee
/// Deprecated: This message is no longer usable. It is only still included for
/// backwards compatibility (e.g. looking up old governance proposals).
/// It is replaced by providing a MsgUpdateMsgFeeProposalRequest in a governance proposal.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateMsgFeeProposal {
    /// propsal title
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    /// propsal description
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// type url of msg to update fee
    #[prost(string, tag = "3")]
    pub msg_type_url: ::prost::alloc::string::String,
    /// additional fee for msg type
    #[prost(message, optional, tag = "4")]
    pub additional_fee: ::core::option::Option<cosmos_sdk_proto::cosmos::base::v1beta1::Coin>,
    /// optional recipient to recieve basis points
    #[prost(string, tag = "5")]
    pub recipient: ::prost::alloc::string::String,
    /// basis points to use when recipient is present (1 - 10,000)
    #[prost(string, tag = "6")]
    pub recipient_basis_points: ::prost::alloc::string::String,
}
/// RemoveMsgFeeProposal defines a governance proposal to delete a current msg based fee
/// Deprecated: This message is no longer usable. It is only still included for
/// backwards compatibility (e.g. looking up old governance proposals).
/// It is replaced by providing a MsgRemoveMsgFeeProposalRequest in a governance proposal.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveMsgFeeProposal {
    /// propsal title
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    /// propsal description
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// type url of msg fee to remove
    #[prost(string, tag = "3")]
    pub msg_type_url: ::prost::alloc::string::String,
}
/// UpdateNhashPerUsdMilProposal defines a governance proposal to update the nhash per usd mil param
/// Deprecated: This message is no longer usable. It is only still included for
/// backwards compatibility (e.g. looking up old governance proposals).
/// It is replaced by providing a MsgUpdateNhashPerUsdMilProposalRequest in a governance proposal.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateNhashPerUsdMilProposal {
    /// proposal title
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    /// proposal description
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// nhash_per_usd_mil is number of nhash per usd mil
    #[prost(uint64, tag = "3")]
    pub nhash_per_usd_mil: u64,
}
/// UpdateConversionFeeDenomProposal defines a governance proposal to update the msg fee conversion denom
/// Deprecated: This message is no longer usable. It is only still included for
/// backwards compatibility (e.g. looking up old governance proposals).
/// It is replaced by providing a MsgUpdateConversionFeeDenomProposalRequest in a governance proposal.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateConversionFeeDenomProposal {
    /// proposal title
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    /// proposal description
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// conversion_fee_denom is the denom that usd will be converted to
    #[prost(string, tag = "4")]
    pub conversion_fee_denom: ::prost::alloc::string::String,
}
